from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
driver = webdriver.Chrome("C:\Python\Python37\Doc")
driver.get("http://www.baidu.com")
driver.find_element_by_id('kw').send_keys('hello')
time.sleep(2)
driver.find_element_by_id('kw').send_keys(Keys.BACK_SPACE)
time.sleep(2)
driver.find_element_by_id('kw').send_keys(Keys.SPACE)
time.sleep(2)
driver.find_element_by_id('kw').send_keys(Keys.CONTROL,'a')
time.sleep(2)
driver.find_element_by_id('kw').send_keys(Keys.CONTROL,'x')
time.sleep(2)
driver.find_element_by_id('kw').send_keys(Keys.CONTROL,'v')
time.sleep(2)
driver.find_element_by_id('kw').send_keys(Keys.ENTER)
time.sleep(2)
driver.quit()